---
title: "Article de William G. Meikle"
output:
  bookdown::pdf_document2:
    toc: true
fontsize: 12pt
lang: fr
---
```{r chunksetup, include = FALSE}
library('knitr')
opts_chunk$set(comment = '', echo = FALSE,  tidy = TRUE, 
               fig.pos = 'ht!', fig.align='center')
```
\newpage
# Introduction
Cet article regroupe différentes études qui avaient pour objectif d'analyser les changements de poids dans une ruche en une journée selon différents facteurs environementaux afin de mesurer leurs effets sur les colonies d'abeilles. 
Le changement de poids des ruches peut être causé par plusieurs facteurs incluant :
\begin{itemize}
  \item le départ et l'arrivée des butineuses
  \item l'augmentation et la perte d'humidité et de nectar
\end{itemize}
Durant les différentes études, trois hypothèses seront testés :
\begin{itemize}
  \item la malnutrition des abeilles
  \item le départ des butineuses retardées
  \item le déplacement des ruches dans d'autres conditions météorologiques
\end{itemize}
Les résultats de cette recherche sont nombreux mais on ne s'intéressera qu'à ceux ...

# Modélisation 
L'objectif est de modéliser le changement de poids par régression par morceaux. Pour cela, ils commençent par éliminer la tendance des données en soustrayant le poids enregistré, à minuit, à celle de chaque moment de la journée.\newline

## Fonction "segmented"
Le changement de poids dans la journée peut se modéliser dans R par la fonction "segmented". Cette fonction peut aussi de déterminer le nombre de points de rupture mais elle tend à surestimer le nombre pour que l'estimation soit préférable pour le modèle final.\newline
Les sorties de la fonction sont les valeurs finales des points de rupture, les pentes et les intercepts des segments.

## Points de rupture
DESCRIPTION DES FIGURES

Afin de s'assurer que le modèle n'ait pas trop de paramètres arbitraires et qu'on reflète avec précision le changement de poids, il faut tester le modèle avec un nombre de points de rupture minimal. La plupart des modèles sur des activités quotidiennes ont entre quatre et six segments et les points de rupture entre le crépuscule et l'aube sont considérés comme des erreurs : le modèle à trois points de rupture est donc celui ayant le moins de points de rupture.\newline
Afin de déterminer le meilleur modèle entre celui à trois, quatre ou cinq points de rupture, il faut comparer différents paramètres :
\begin{itemize}
  \item pour chaque ajustement, la moyenne ajustée $R^{2}$
  \item le nombre de jours où chaque ajustement ont réussi
  \item le pourcentage d'ajustement réussi
  \item le nombre d'erreurs pour les premiers et les derniers points de rupture
\end{itemize}
On trouve finalement que le modèle à trois points de rupture est celui ayant les valeurs de $R^{2}$ plus basses en moyenne. À l'inverse, le modèle à cinq points de rupture est celui ayant les valeurs de $R^{2}$ les plus hautes en moyenne.
En testant sur plusieurs bases de données, le modèle à quatre points de rupture est celui ayant le meilleur ajustement

# Résultats
On se rend compte que le changement de poids s'étend sur trois parties principales, en prenant l'aube comme le départ initial des butineuses et le crépuscule comme leur retour :
\begin{itemize}
  \item de minuit à l'aube : changement de poids causés par les effets de température (vapeur d'eau,...)
  \item de l'aube au crépuscule (période active) : 
  \item du crépuscule à minuit : colonie en repos
\end{itemize}
