---
title: "segmented"
output: pdf_document
date: "2025-03-10"
---




```{r, echo=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("/Users/coralie.romani/Desktop/PROJET/BD/Weight_2023_Sica_Confoux.xlsx")

# Créer une liste des noms des ruches (ajuster si nécessaire)
noms_ruches <- colnames(poids)[2:13]

# Créer une liste vide pour stocker les graphiques
graphes_ruches <- list()

# Boucle pour créer un graphique pour chaque ruche
for (ruche in noms_ruches) {
  
  # Extraire les données pour la ruche
  poids_restreint <- poids[as.Date(poids$date) == as.Date("2023-06-04"), c("date", ruche)]
  
  # Renommer la colonne de poids
  colnames(poids_restreint)[2] <- "poids_ruches"
  
  # Convertir la date en format numérique
#  poids_restreint$date_num <- as.numeric(poids_restreint$date)
  poids_restreint$date_num <- c(seq(1:24))
  # Ajuster un modèle linéaire simple
  modele <- lm(poids_ruches ~ date_num, data = poids_restreint)
  
  # Ajuster le modèle segmenté
# modele_segmenté <- segmented(modele, seg.Z = ~date_num, npsi = 3)
 modele_segmenté <- segmented(modele, seg.Z = ~date_num,npsi=3, psi = list(date_num= c(18,12,6)))
  # Créer le graphique
  graphique <- ggplot(poids_restreint, aes(x = date, y = poids_ruches)) +
    geom_point() +
    geom_line() +
    geom_line(aes(y = predict(modele_segmenté, newdata = poids_restreint)), color = "blue") +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "red") +  # Régression linéaire globale
    labs(title = paste(ruche), 
         x = "Heure", y = "Poids de la ruche") +
    theme_minimal()
  
    graphes_ruches[[ruche]] <- graphique
    print(graphique)
}
```


# Régression segmentée du poids moyen des 12 ruches sur 1 journée
```{r, echo=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("/Users/coralie.romani/Desktop/PROJET/BD/Weight_2023_Sica_Confoux.xlsx")


# Créer une liste des noms des ruches (ajuster si nécessaire)
noms_ruches <- colnames(poids)[2:13]


  # Extraire les données pour la ruche
  poids_restreint <- subset(poids, date <= "2023-06-04 23:00:00" & date >= "2023-06-04 00:00:00")
 
  poids_moyen <- data.frame(date = poids_restreint$date, poids = rowMeans(poids_restreint[,-1])) 
  # Renommer la colonne de poids
  colnames(poids_restreint)[2] <- "poids_ruches"
  
  # Convertir la date en format numérique
  poids_moyen$date_num <- as.numeric(poids_restreint$date)
  
  # Ajuster un modèle linéaire simple
  modele <- lm(poids ~ date_num, data = poids_moyen)
  
  # Ajuster le modèle segmenté
  modele_segmente <- segmented(modele, seg.Z = ~date_num, npsi = 4)
  
  # Créer le graphique
  graphique <- ggplot(poids_moyen, aes(x = date, y = poids)) +
    geom_point() +
  
    geom_line(aes(y = predict(modele_segmente, newdata = poids_moyen)), color = "blue") +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "red") +  # Régression linéaire globale
    labs(title = ruche, 
         x = "Heure", y = "Poids de la ruche") +
    theme_minimal()
    print(graphique)
```