---
title: "segmented"
output: pdf_document
date: "2025-03-10"
---


# RL ségmentée sur un jour pour les 6 ruches de Sica (6 graphiques)

```{r, echo='FALSE', warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("../../BD/Weight_2023_Sica_Confoux.xlsx")

colnames(poids) <- c("date", "Confoux - 412", "Confoux - 409", "Confoux - 435",
                            "Confoux - 430", "Confoux - 404", "Confoux - 405",
                            "Sica - 415", "Sica - 428", "Sica - 444",
                            "Sica - 412", "Sica - Y", "Sica - 89")

poids_sica <- poids %>%
  select(1,(ncol(poids)-5):ncol(poids))

# Créer une liste des noms des ruches (ajuster si nécessaire)
noms_ruches <- colnames(poids_sica)[2:7]

graphes_ruches <- list()

for (ruche in noms_ruches) {
  
  # Extraire les données pour la ruche
  poids_restreint <- poids[as.Date(poids_sica$date) == as.Date("2023-04-12"), c("date", ruche)]
  colnames(poids_restreint)[2] <- "poids"
  
  # Convertir la date en format numérique
  poids_restreint$date_num <- as.numeric(poids_restreint$date)
  
  modele <- lm(poids ~ date_num, data = poids_restreint)
  
  modele_segmente <- segmented(modele, seg.Z = ~date_num, npsi=4)
  # Créer le graphique
  graphique <- ggplot(poids_restreint, aes(x = date, y = poids)) +
    geom_point() +
    geom_line(aes(y = predict(modele_segmente, newdata = poids_restreint)), color = "blue") +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "red") +  # Régression linéaire globale
    labs(x = "Heure", y = "Poids moyen (en kg)") +
    theme_minimal()
  
    graphes_ruches[[ruche]] <- graphique
    print(graphique)
}
```


# RL segmentée du poids moyen des 6 rûches de Sica sur 1 journée type : 10 avril 2023

```{r, echo=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("../../BD/Weight_2023_Sica_Confoux.xlsx")

colnames(poids) <- c("date", "Confoux - 412", "Confoux - 409", "Confoux - 435",
                            "Confoux - 430", "Confoux - 404", "Confoux - 405",
                            "Sica - 415", "Sica - 428", "Sica - 444",
                            "Sica - 412", "Sica - Y", "Sica - 89")

poids_sica <- poids[, c(1, 8:13)]

# Extraire les données pour la rûche
poids_restreint2 <- subset(poids_sica, date <= "2023-04-11 01:00:00" & date >= "2023-04-10 02:00:00")

poids_moyen <- data.frame(date = poids_restreint2$date, poids = rowMeans(poids_restreint2[,-1])) 

colnames(poids_restreint2)[2] <- "poids"

poids_moyen$date_num <- as.numeric(poids_restreint2$date)
modele <- lm(poids ~ date_num, data = poids_moyen)

modele_segmente <- segmented(modele, seg.Z = ~date_num, npsi = 4, silent = TRUE)

# Extraire les breakpoints (estimation)
breakpoints <- modele_segmente$psi[, "Est."]

# Convertir les breakpoints numériques en dates
breakpoints_dates <- as.POSIXct(breakpoints)

# Début et fin des données (réels)
start_date <- poids_moyen$date[1]
end_date <- poids_moyen$date[nrow(poids_moyen)]
start_p <- poids_moyen$poids[1]
end_p <- poids_moyen$poids[nrow(poids_moyen)]

# Poids prédit aux premiers et derniers breakpoints
first_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[1]))
last_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[length(breakpoints)]))

# Dates converties
first_bp_date <- breakpoints_dates[1]
first_bp_date2 <- breakpoints_dates[4]

# Tracer
ggplot(poids_moyen, aes(x = date, y = poids)) +
  geom_point() +
  labs(x = "Heure", y = "Poids moyen (en kg)") +

  # Segment 1
  geom_line(data = data.frame(date = c(end_date, first_bp_date),
                              poids = c(end_p, first_bp_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +

  # Segment 2
  geom_line(data = data.frame(date = breakpoints_dates,
                              poids = predict(modele_segmente, newdata = data.frame(date_num = breakpoints))),
            aes(x = date, y = poids), color = "blue", size = 1) +
# Segment 3
  geom_line(data = data.frame(date = c(first_bp_date2 , start_date),
                              poids = c(last_bp_p, start_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +
  # Points rouges aux breakpoints
  geom_point(data = data.frame(date = breakpoints_dates,
                               poids = predict(modele_segmente, newdata = data.frame(date_num = breakpoints))),
             aes(x = date, y = poids), color = "red", size = 3) +
  scale_x_datetime(
  labels = scales::date_format("%H:%M"),
  limits = c(as.POSIXct("2023-04-10 00:00:00"),
             as.POSIXct("2023-04-11 01:00:00"))
) +
  theme_minimal()

```

# RL segmentée du poids moyen des 6 rûches de Sica sur 1 journée type : 13 octobre 2023

```{r, echo=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("../../BD/Weight_2023_Sica_Confoux.xlsx")

colnames(poids) <- c("date", "Confoux - 412", "Confoux - 409", "Confoux - 435",
                            "Confoux - 430", "Confoux - 404", "Confoux - 405",
                            "Sica - 415", "Sica - 428", "Sica - 444",
                            "Sica - 412", "Sica - Y", "Sica - 89")

poids_sica <- poids[, c(1, 8:13)]

# Extraire les données pour la rûche
poids_restreint2 <- subset(poids_sica, date <= "2023-10-14 01:00:00" & date >= "2023-10-13 02:00:00")

poids_moyen <- data.frame(date = poids_restreint2$date, poids = rowMeans(poids_restreint2[,-1])) 

colnames(poids_restreint2)[2] <- "poids"

poids_moyen$date_num <- as.numeric(poids_restreint2$date)
modele <- lm(poids ~ date_num, data = poids_moyen)

modele_segmente <- segmented(modele, seg.Z = ~date_num, npsi = 4, silent = TRUE)

# Extraire les breakpoints (estimation)
breakpoints <- modele_segmente$psi[, "Est."]

# Convertir les breakpoints numériques en dates
breakpoints_dates <- as.POSIXct(breakpoints)

# Début et fin des données (réels)
start_date <- poids_moyen$date[1]
end_date <- poids_moyen$date[nrow(poids_moyen)]
start_p <- poids_moyen$poids[1]
end_p <- poids_moyen$poids[nrow(poids_moyen)]

# Poids prédit aux premiers et derniers breakpoints
first_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[1]))
last_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[length(breakpoints)]))

# Dates converties
first_bp_date <- breakpoints_dates[1]
first_bp_date2 <- breakpoints_dates[4]

last_bp_date <- breakpoints_dates[length(breakpoints)]

# Tracer
ggplot(poids_moyen, aes(x = date, y = poids)) +
  geom_point() +
  labs(x = "Heure", y = "Poids moyen (en kg)") +

  # Segment 1
  geom_line(data = data.frame(date = c(end_date, first_bp_date),
                              poids = c(end_p, first_bp_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +

  # Segment 2
  geom_line(data = data.frame(date = breakpoints_dates,
                              poids = predict(modele_segmente, newdata = data.frame(date_num = breakpoints))),
            aes(x = date, y = poids), color = "blue", size = 1) +
# Segment 3
  geom_line(data = data.frame(date = c(first_bp_date2 , start_date),
                              poids = c(last_bp_p, start_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +
  # Points rouges aux breakpoints
  geom_point(data = data.frame(date = breakpoints_dates,
                               poids = predict(modele_segmente, newdata = data.frame(date_num = breakpoints))),
             aes(x = date, y = poids), color = "red", size = 3) +
  scale_x_datetime(
  labels = scales::date_format("%H:%M"),
  limits = c(as.POSIXct("2023-10-13 00:00:00"),
             as.POSIXct("2023-10-14 01:00:00"))
) +
  theme_minimal()

```

```{r, echo=FALSE, warning=FALSE}
library(readxl)
library(ggplot2)
library(segmented)
library(gridExtra)

# Charger les données
poids <- read_excel("../../BD/Weight_2023_Sica_Confoux.xlsx")

colnames(poids) <- c("date", "Confoux - 412", "Confoux - 409", "Confoux - 435",
                            "Confoux - 430", "Confoux - 404", "Confoux - 405",
                            "Sica - 415", "Sica - 428", "Sica - 444",
                            "Sica - 412", "Sica - Y", "Sica - 89")

poids_sica <- poids[, c(1, 8:13)]

# Extraire les données pour la rûche
poids_restreint2 <- subset(poids_sica, date <= "2023-06-12 01:00:00" & date >= "2023-06-11 02:00:00")

poids_moyen <- data.frame(date = poids_restreint2$date, poids = rowMeans(poids_restreint2[,-1])) 

colnames(poids_restreint2)[2] <- "poids"

poids_moyen$date_num <- as.numeric(poids_restreint2$date)
modele <- lm(poids ~ date_num, data = poids_moyen)

modele_segmente <- segmented(modele, seg.Z = ~date_num, npsi = 1, silent = TRUE)

# Extraire les breakpoints (estimation)
breakpoints <- modele_segmente$psi[, "Est."]

# Convertir les breakpoints numériques en dates
breakpoints_dates <- as.POSIXct(breakpoints)

# Début et fin des données (réels)
start_date <- poids_moyen$date[1]
end_date <- poids_moyen$date[nrow(poids_moyen)]
start_p <- poids_moyen$poids[1]
end_p <- poids_moyen$poids[nrow(poids_moyen)]

# Poids prédit aux premiers et derniers breakpoints
first_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[1]))
last_bp_p <- predict(modele_segmente, newdata = data.frame(date_num = breakpoints[length(breakpoints)]))

# Dates converties
first_bp_date <- breakpoints_dates[1]
first_bp_date2 <- breakpoints_dates[4]

ggplot(poids_moyen, aes(x = date, y = poids)) +
  geom_point() +
  labs(x = "Heure", y = "Poids moyen (en kg)") +

  # Segment 1 : du début au breakpoint
  geom_line(data = data.frame(date = c(start_date, first_bp_date),
                              poids = c(start_p, first_bp_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +

  # Segment 2 : du breakpoint à la fin
  geom_line(data = data.frame(date = c(first_bp_date, end_date),
                              poids = c(first_bp_p, end_p)),
            aes(x = date, y = poids), color = "blue", size = 1) +

  # Point rouge pour le breakpoint
  geom_point(data = data.frame(date = first_bp_date, poids = first_bp_p),
             aes(x = date, y = poids), color = "red", size = 3) +

  scale_x_datetime(
    labels = scales::date_format("%H:%M"),
    limits = c(as.POSIXct("2023-06-11 00:00:00"),
               as.POSIXct("2023-06-12 01:00:00"))
  ) +
  theme_minimal()
```
