---
title: "Article de William G. Meikle"
output:
  bookdown::pdf_document2:
  toc: true
fontsize: 12pt
lang: fr
---
```{r chunksetup, include = FALSE}
library('knitr')
opts_chunk$set(comment = '', echo = FALSE,  tidy = TRUE, 
               fig.pos = 'ht!', fig.align='center')
```
\newpage
# Introduction
L'étude a pour objectif d'analyser les changements de poids dans une ruche au cours d'une journée selon différents facteurs environnementaux afin de mesurer leurs effets sur les colonies d'abeilles.\newline
En procédant à l'analyse de données continues, cela permet de réveler des moments marquants liés au changement de poids des ruches, comme :
\begin{itemize}
  \item le départ et l'arrivée des butineuses
\item l'augmentation et la perte d'humidité et de nectar
\end{itemize}
Durant cette étude, trois hypothèses seront testés afin de valider les interprétations des variations de poids :
  \begin{itemize}
\item la malnutrition des abeilles
\item le départ des butineuses retardées
\item le déplacement des ruches dans d'autres conditions environnementaux
\end{itemize}
Les résultats de cette recherche sont nombreux mais dans le cadre de notre projet, on ne s'intéressera qu'à ceux ...

# Modélisation 
L'objectif est de modéliser le changement de poids par régression par morceaux. Pour obtenir un ensemble de données indépendantes, ils commencent par éliminer la tendance en soustrayant le poids enregistré à minuit de celui enregistré à chaque instant de la journée.\newline
Le second objectif était de déterminer à quel point la pente du segment de la régression par morceaux est impacté par les changements environnementaux et par l'activité des abeilles.

## Méthodes utilisées
La méthode des Moyennes Mobiles donne des estimations robustes.

## Fonction "segmented"
Le changement de poids dans la journée peut se modéliser dans R par la fonction "segmented". En effet, cette méthode a été utilisée pour tester différentes structures de modèles (à trois, quatre et cinq points de rupture). Cette fonction peut aussi déterminer le nombre de points de rupture mais elle tend à surestimer le nombre pour que l'estimation soit préférable pour le modèle final.\newline
Les sorties de la fonction sont les valeurs finales des points de rupture, les pentes et les intercepts des segments.\newline
À COMPLÉTER

## Points de rupture
Afin de s'assurer que le modèle n'ait pas trop de paramètres arbitraires et qu'on reflète avec précision le changement de poids, il faut tester le modèle avec un nombre de points de rupture minimal. La plupart des modèles sur des activités quotidiennes ont entre quatre et six segments et les points de rupture entre le crépuscule et l'aube sont considérés comme des erreurs : le modèle à trois points de rupture est donc celui étant minimal.\newline
Afin de déterminer le meilleur modèle entre celui à trois, quatre ou cinq points de rupture, il faut comparer différents paramètres :
  \begin{itemize}
\item pour chaque ajustement, la moyenne ajustée $R^{2}$
  \item le nombre de jours où chaque ajustement est réussi
\item le pourcentage d'ajustement réussi
  \item le nombre d'erreurs pour les premiers et les derniers points de rupture
\end{itemize}
On trouve finalement que le modèle à trois points de rupture est celui ayant les valeurs de $R^{2}$ plus basses en moyenne. À l'inverse, le modèle à cinq points de rupture est celui ayant les plus hautes en moyenne.
Finalement, en testant sur plusieurs bases de données, le modèle à quatre points de rupture est celui ayant le meilleur ajustement.

## Pente de la régression
Afin d’évaluer plus précisément l’impact de l’activité des abeilles sur les changements de poids, la pente de la régression a été analysée. La pente de la régression est associée aux mouvements net des abeilles. En effet, Ll pente de la régression reflète l’activité des abeilles : plus la pente est forte, plus le flux d’abeilles entrant et sortant est important. Cela permet d’estimer indirectement la quantité de nectar rapportée.

# Résultats
On se rend compte que le changement de poids s'étend sur trois parties principales, en prenant l'aube comme le départ initial des butineuses (baisse significative du poids) et le crépuscule comme leur retour (hausse significative) :
\begin{itemize}
  \item de minuit à l'aube : changement de poids causés par les effets de température (humidité,...)
\item de l'aube au crépuscule (période active) : légère baisse du poids causée par le départ progressif des abeilles
  \item du crépuscule à minuit : colonie en repos, stabilisation du poids
\end{itemize}
Les résultats ont montré que les changements de poids suivaient un cycle défini sur une journée permettant d'identifier l'heure de départ et d'arrivée des abeilles mais aussi approximativement, la quantité de nectar transportée.\newline
Finalement, cette étude a permis de démontrer que la surveillance en continu des poids des ruches permet de surveiller l'état des colonies sans intervention directe mais aussi de détecter les différences entre des colonises bien nourris et malnourries/stressées.\newline
Les estimations des départs et des arrivées des butineuses divergent pendant l'hiver et le printemps (cela est causé par les changements de températures et d'heures)

# Analyse des figures
## Figure 1
La figure 1 présente l'évolution du poids moyen des ruches de mars à avril, en Californie. Le graphe A montre une baisse du poids en mars suivie d'une augmentation en avril. Cette tendance suggère une collecte de nectar seulement à partir d'avril. Le graphe B met en évidence les cycles journaliers des changements de poids : baisse le matin (aux départs des butineuses), hausse significative (aux retours des butineuses chargées de nectar). On remarque aussi que l'intensité de la variation du poids en avril augmente ce qui pourrait être en rapport avec l'augmentation de la floraison.
                                                                                                      
## Figure 2
Cette figure présente des données similaires à la figure 1, mais en Arizona. De même, on remarque un cycle journalier plus constant sur la période mais ayant des variations intra-journaliers plus intenses que ceux de Californie. Cependant, ici, on observe une augmentation continue du poids ce qui pourrait indiquer un accès constant au nectar. 
                                                                                                      
## Figure 3
Cette figure présente deux graphiques à deux périodes de l'année différente (une en mars et une en avri), en Californie. Ces deux dates sont significatives après avoir vu à la figure 1, que la collecte de nectar ne semble commencer qu'à partir d'avril.\newline
Plusieurs phases marquantes peuvent être identifiées sur les deux graphiques : 
\begin{itemize}
  \item de minuit à 8h (période inactive) : poids stable, variations causées par l'humidité
  \item à 8h (aube) : départ des butineuses
  \item de 8h à 9h ou 16h (selon la date) : perte de poids continu
  \item à 9h ou 16h : point de rupture où plus d'abeilles rentrent que ne partent (hausse du poids)
  \item de 9h ou 16h à 20h (selon la date) : hausse continu du poids (due aux abeilles et au nectar/pollen rapporté)
  \item à 20h (crépuscule) : fin du retour des butineuses
  \item de 20h à minuit (période inactive) : poids stable, variations causées par l'humidité
\end{itemize}
Ces informations permettent d'affiner le modèle de régression par morceaux. De plus, cela permet de prouver que nous pouvons déterminer l'activité des colonies uniquement à partir du poids des ruches.
                                                                                                      
## Figure 4
Cette figure compare trois modèles de régression par morceaux appliqués aux données d'une journée type, en avril, en Californie. Ces trois modèles se distinguent par leur nombre de points de rupture : 3, 4 ou 5.\newline
Le modèle à 3 points de rupture ne détecte pas réellement le départ des butineuses.\newline
Le modèle à 5 points de rupture risque de surajuster le modèle qui compliquerait l'interprétation des résultats.\newline
Finalement, le modèle à 4 points de rupture semble être le plus adéquat, en détectant les phases principales vu précédemment à la figure 3.
                                                                                                      
## Figure 5
La figure présente 2 graphiques illustrant les variations intra-journaliers en mars et en avril, correspondant respectivement aux périodes précédant et suivant la floraison.\newline
Avant la floraison, on observe une faible augmentation du poids au retour des butineuses (sûrement à cause des ressources limitées), tandis qu'après la floraison, on distingue une forte augmentation du poids due aux butineuses ramenant beaucoup plus de nectar.\newline
Cette comparaison prouve l'impact direct de la floraison (changement environnemental) sur l'activité des abeilles.

## Figure 6
Nous avons trois graphiques, allant de février à juin, montrant :
\begin{itemize}
  \item l'heure du premier et du dernier point de rupture (ceux du départ et du retour des butineuses)
  \item le premier et le dernier changement de poids de la journée
  \item les températures et les précipitations
\end{itemize}
Nous remarquons, sur le premier graphique, un décalage progressif des heures de départ et de retour, causé par le changement d'heures et donc par le changement de saison.\newline
Sur le graphique 2, nous observons qu'à la période de miellée, il y a une plus grande perte de poids durant la nuit ce qui est surement causé par l'évaporation du nectar qui est en plus grande quantité.\newline
Le dernier graphique nous confirme que le climat influence l'activité des colonies.
                                                                                                      
## Figure 7
La figure 7 présente les données de la même façon que la figure 6, mais pour les ruches en Arizona.
Nous remarquons, sur le premier graphique, la même tendance qu'en Californie mais avec un décalage moins prononcé.\newline
Sur le graphique 2, nous observons qu'à la période de miellée, le gain de poids durant la nuit est moins important qu'en Californie (évaporation plus rapide ? climat plus sec ?).\newline
Le dernier graphique nous montre que l'effet des températures est plus marqué ce qui oblige les abeilles à s'adapter à des conditions plus chaudes et plus sèches.

## Figure 8
Cette figure présente deux graphiques comparant le changement de poids des colonies bien nourris et malnourris à deux périodes de l'année différente (en février et en mars).\newline
Pendant la pollinisation, les colonies bien nourries ont un gain de poids plus important en fin de journée ce qui montre une plus grande collecte de nectar.\newline
Après la pollinisation, ces mêmes colonies ont une perte de poids plus importante le matin, indiquant un départ plus rapide des butineuses.\newline
Ces différences montrent que la nutrition influence l’intensité de l’activité des abeilles mais pas nécessairement leurs horaires de sortie et de retour.\newline
Les colonies bien nourries sont plus dynamiques, avec une meilleure collecte de nectar pendant la pollinisation et un départ plus rapide après cette période. Les colonies mal nourries ont une activité plus faible, ce qui pourrait être lié à un manque de ressources.